
spring:
  datasouse:
    type: com.alibaba.druid.pool.DruidDataSouse
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springCloud?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "gqs123456"
    
config:
  info: "master branch,config-repo config-dev.yml version=8"
